# Form implementation generated from reading ui file 'mainForm2.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(605, 549)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.AddButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.AddButton.setGeometry(QtCore.QRect(10, 440, 171, 51))
        self.AddButton.setObjectName("AddButton")
        self.tableView = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(10, 20, 571, 401))
        self.tableView.setObjectName("tableView")
        self.EditButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.EditButton.setGeometry(QtCore.QRect(200, 440, 171, 51))
        self.EditButton.setObjectName("EditButton")
        self.DeleteButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.DeleteButton.setGeometry(QtCore.QRect(390, 440, 171, 51))
        self.DeleteButton.setObjectName("DeleteButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 605, 22))
        self.menubar.setObjectName("menubar")
        self.FuchersBar = QtWidgets.QMenu(parent=self.menubar)
        self.FuchersBar.setObjectName("FuchersBar")
        self.TableBar = QtWidgets.QMenu(parent=self.menubar)
        self.TableBar.setObjectName("TableBar")
        self.CalcBar = QtWidgets.QMenu(parent=self.menubar)
        self.CalcBar.setObjectName("CalcBar")
        self.ReportBar = QtWidgets.QMenu(parent=self.menubar)
        self.ReportBar.setObjectName("ReportBar")
        self.HelpBar = QtWidgets.QMenu(parent=self.menubar)
        self.HelpBar.setObjectName("HelpBar")
        MainWindow.setMenuBar(self.menubar)
        self.action_5 = QtGui.QAction(parent=MainWindow)
        self.action_5.setObjectName("action_5")
        self.Statistika = QtGui.QAction(parent=MainWindow)
        self.Statistika.setObjectName("Statistika")
        self.Kontrakti = QtGui.QAction(parent=MainWindow)
        self.Kontrakti.setObjectName("Kontrakti")
        self.Union = QtGui.QAction(parent=MainWindow)
        self.Union.setObjectName("Union")
        self.TableBar.addAction(self.Statistika)
        self.TableBar.addAction(self.Kontrakti)
        self.TableBar.addAction(self.Union)
        self.menubar.addAction(self.FuchersBar.menuAction())
        self.menubar.addAction(self.TableBar.menuAction())
        self.menubar.addAction(self.CalcBar.menuAction())
        self.menubar.addAction(self.ReportBar.menuAction())
        self.menubar.addAction(self.HelpBar.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.AddButton.setText(_translate("MainWindow", "Добавить"))
        self.EditButton.setText(_translate("MainWindow", "Редактировать"))
        self.DeleteButton.setText(_translate("MainWindow", "Удалить"))
        self.FuchersBar.setTitle(_translate("MainWindow", "Фьючерсы"))
        self.TableBar.setTitle(_translate("MainWindow", "Таблицы"))
        self.CalcBar.setTitle(_translate("MainWindow", "Расчёт"))
        self.ReportBar.setTitle(_translate("MainWindow", "Отчетность"))
        self.HelpBar.setTitle(_translate("MainWindow", "Справка"))
        self.action_5.setText(_translate("MainWindow", "Фт"))
        self.Statistika.setText(_translate("MainWindow", "Статистика торгов"))
        self.Kontrakti.setText(_translate("MainWindow", "Контраккты"))
        self.Union.setText(_translate("MainWindow", "Объединение"))


'''if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())'''
